# https://surge.mitsea.com/ https://manual.nssurge.com/ （英文版比较齐全）
[General]
  ipv6 = false
  loglevel = notify
  skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, e.crashlytics.com, captive.apple.com
  dns-server = system, 223.5.5.5, 114.114.114.114
  hijack-dns = 8.8.8.8:53
  geoip-maxmind-url = https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/lite/Country.mmdb
  hide-vpn-icon=true  
  [SSID Setting]
  "Tencent-WiFi" suspend=true
  "NETGEAR28_5G" suspend=true