name: Sync main branch workflow to master branch
on:
  push:
    branches:
      - main

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Copy file from main branch
        run: |
          git checkout main -- .github/workflows/update-rule-list.yml

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/update-rule-list.yml
          git commit -m "Sync update-rule-list.yml from main branch"
          git push